const pool = require("../config/db");
const PDFDocument = require("pdfkit");
const path = require("path");
const fs = require("fs");

/* =========================
   TENANT PRINT (PDF)
========================= */
exports.printTenant = async (req, res) => {
  try {
    const { id, owner_id } = req.body;

    const [[tenant]] = await pool.query(
      "SELECT * FROM tenant WHERE id=? AND owner_id=?",
      [id, owner_id]
    );

    if (!tenant) {
      return res.status(404).send("Tenant not found");
    }

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `inline; filename=tenant_${tenant.id}.pdf`
    );

    const doc = new PDFDocument({ margin: 40 });
    doc.pipe(res);

    /* ---------- HEADER ---------- */
    doc
      .fontSize(18)
      .text("Tenant Details", { align: "center" })
      .moveDown(1.5);

    /* ---------- IMAGE ---------- */
    if (tenant.image_path) {
      const imgPath = path.join(process.cwd(), tenant.image_path);
      if (fs.existsSync(imgPath)) {
        doc.image(imgPath, 400, 80, { width: 120 });
      }
    }

    doc.moveDown(2);

    const label = (l, v) => {
      doc
        .fontSize(10)
        .text(`${l}: `, { continued: true })
        .fontSize(11)
        .text(v || "-");
      doc.moveDown(0.4);
    };

    /* ---------- DATA ---------- */
    label("Tenant Name", tenant.tenant_full_name);
    label("Mobile No", tenant.mobile_no);
    label("Aadhar No", tenant.aadhar_no);
    label("PAN Card", tenant.pan_card);
    label("Passport", tenant.passport);
    label("Age", tenant.age);

    doc.moveDown(0.5);

    label("Previous Address", tenant.previous_address);
    label("Permanent Address", tenant.permanent_address);

    doc.moveDown(0.5);

    label("Nature of Work", tenant.nature_of_work);
    label("Office Address", tenant.office_address_with_contact);

    doc.moveDown(0.5);

    label("Reference 1", tenant.ref1_name_address_with_contact);
    label("Reference 2", tenant.ref2_name_address_with_contact);
    label("Agent", tenant.agent_name_address_with_contact);

    doc.moveDown(0.5);

    label(
      "Agreement Start",
      tenant.period_of_aggrement
        ? new Date(tenant.period_of_aggrement).toLocaleDateString()
        : "-"
    );

    label(
      "Agreement End",
      tenant.maturity_of_aggrement
        ? new Date(tenant.maturity_of_aggrement).toLocaleDateString()
        : "-"
    );

    /* ---------- FOOTER ---------- */
    doc.moveDown(2);
    doc
      .fontSize(9)
      .text("Generated by Rent Management System", { align: "center" });

    doc.end();
  } catch (err) {
    console.error(err);
    res.sendStatus(500);
  }
};
